// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFyxtLmjSjw1LNpz3uICYq5yRl8bgITBU',
    appId: '1:623349200934:web:c9ace2e32d6bf77a614ee7',
    messagingSenderId: '623349200934',
    projectId: 'scheduller-app-aee2f',
    authDomain: 'scheduller-app-aee2f.firebaseapp.com',
    storageBucket: 'scheduller-app-aee2f.firebasestorage.app',
    measurementId: 'G-DE4JQY19F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3AP9Qsk-jIJjoQbVU_lryzHTHkpsneiM',
    appId: '1:623349200934:android:ba7ec5c7cf86844d614ee7',
    messagingSenderId: '623349200934',
    projectId: 'scheduller-app-aee2f',
    storageBucket: 'scheduller-app-aee2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuTjVg01yKwJ1-ngy1MNTu5W1io726rPU',
    appId: '1:623349200934:ios:7093fe681774d87f614ee7',
    messagingSenderId: '623349200934',
    projectId: 'scheduller-app-aee2f',
    storageBucket: 'scheduller-app-aee2f.firebasestorage.app',
    iosBundleId: 'com.example.schedullerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuTjVg01yKwJ1-ngy1MNTu5W1io726rPU',
    appId: '1:623349200934:ios:7093fe681774d87f614ee7',
    messagingSenderId: '623349200934',
    projectId: 'scheduller-app-aee2f',
    storageBucket: 'scheduller-app-aee2f.firebasestorage.app',
    iosBundleId: 'com.example.schedullerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFyxtLmjSjw1LNpz3uICYq5yRl8bgITBU',
    appId: '1:623349200934:web:876368257596f1c0614ee7',
    messagingSenderId: '623349200934',
    projectId: 'scheduller-app-aee2f',
    authDomain: 'scheduller-app-aee2f.firebaseapp.com',
    storageBucket: 'scheduller-app-aee2f.firebasestorage.app',
    measurementId: 'G-FW9B3F8YHW',
  );

}